version: "3.9"

services:
  tanggalan-api:
    build:
      context: .
      target: runtime
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - ./data:/app/data
    restart: always
    command: ./server

  migrate:
    build:
      context: .
      target: migrator
    env_file: .env
    volumes:
      - ./data:/app/data
    entrypoint: ./scripts/init_db.sh
